### ISSUE TITLE
Wrong value validation

### ISSUE THREAD

**Issue by park-rat** [Soluyankp91/Lab1_Renju#1]
Consider validating the values while reading input file.
By definition allowed characters are 0 1 and 2.
Your validation of int(num) allows values like 5.
https://github.com/Soluyankp91/Lab1_Renju/blob/bc9ddf2a38a7f8f29f66b4e44580bfa0c67e6aeb/Lab1.py#L84

**Comment by Soluyankp91** [comment]
Resolved
