### ISSUE TITLE
Near duplicate functions question

### ISSUE THREAD

**Issue by park-rat** [Soluyankp91/Lab1_Renju#2]
All four functions (check_horizontal, check_vertical, check_diagonal_top_left_bottom_right, check_diagonal_bottom_left_top_right) are duplicates except of 3 lines
https://github.com/Soluyankp91/Lab1_Renju/blob/bc9ddf2a38a7f8f29f66b4e44580bfa0c67e6aeb/Lab1.py#L10
https://github.com/Soluyankp91/Lab1_Renju/blob/bc9ddf2a38a7f8f29f66b4e44580bfa0c67e6aeb/Lab1.py#L15
https://github.com/Soluyankp91/Lab1_Renju/blob/bc9ddf2a38a7f8f29f66b4e44580bfa0c67e6aeb/Lab1.py#L17
Under what conditions would you address this issue? (each function is >= n lines of code, etc.)
What would be your solution?
Would such solution only introduce unnecessary complications for such small project?
1 - create an interface with three methods (to replace 3 unique lines for each function)
2 - implement it for all four directions
3 - (polymorphism) use the interface in generic function (e.g. check_direction)

**Comment by Soluyankp91** [comment]
I think it's unnecessary to do this for such a small task.

**Comment by Soluyankp91** [comment]
Show me an example of how you want to refactor using one function because I'm not sure I understand you.

**Comment by park-rat** [comment]
```
interface DirectionChecker {  //implemented for four directions
  isCellEligible(board, row, col, color, index);
  areBorderCellsSameColour(board, row, col, color);
  getPosition(row, col);
}

def check_generic(board, row, col, color, DirectionChecker):  //call 4 times for different implementations
    count = 1
    for i in range(1, WINNING_LENGTH):
        if DirectionChecker.isCellEligible(...):
            count += 1
        else:
            break
    if count == WINNING_LENGTH:
        if DirectionChecker.areBorderCellsSameColour(...):
            return 0, None  # More than five consecutive stones
    return count, DirectionChecker.getPosition(...)
```



Please note this is not a request for refactor but a part of a question.

**Comment by Soluyankp91** [comment]
I've refactored everything according to your advice
