### ISSUE TITLE
Small refactor?

### ISSUE THREAD

**Issue by IanaKhitsko** [Soluyankp91/Lab1_Renju#4]
https://github.com/Soluyankp91/Lab1_Renju/blob/bc9ddf2a38a7f8f29f66b4e44580bfa0c67e6aeb/Lab1.py#L22C22-L22C32

Consider to rewrite it like this:

if row + i >= ROW_LENGTH or board[row + i][col] != color:
           break
 count += 1

The same for other similar places.
Thus you will have more compact code.

**Comment by Soluyankp91** [comment]
Resolved
